### ISSUE TITLE
Fix Master Query

### ISSUE THREAD

**Issue by XtalOsc** [XtalOsc/KMOJ_AirTrafficControl#10]

**Comment by dkuntz811** [comment]
What did this mean?

**Comment by benmahowald** [comment]
There were a few things in the master table that weren't being updated when a new contract submits. The only things not being saved in master table now are flight_id, prod_id and copy_id.

**Comment by ThatSpaceGuy** [comment]
flight_id and prod_id do not need to be in the master table.  Each of those tables have the appropriate master_id in them.

**Comment by ThatSpaceGuy** [comment]
I added commands to drop those columns, and I got Copy ID in the Master Query.  This can be closed.
