### ISSUE TITLE
Cart # field missing from "New Contract" view.

### ISSUE THREAD

**Issue by benmahowald** [XtalOsc/KMOJ_AirTrafficControl#29]

**Comment by dkuntz811** [comment]
Isn't cart# assigned by prod or traffic after the new contract has been approved?

**Comment by ThatSpaceGuy** [comment]
Dave is correct. Cart # should not be in "new contract".  If we have a "contracts in progress" view for the UWs it should be there, so that they can see that one has been assigned and/or look up which one has been assigned.

**Comment by benmahowald** [comment]
Oh right. Me dumb. It should go in the prod view. Wait, right? Lol.

**Comment by ThatSpaceGuy** [comment]
Yes. Prod and Traffic should be able to view and edit Cart#.
